# ensure there is enough power reference preview steps left before the full 24 hour mark
simulation_max_time: 3600
simulation_sampling_time: 1.0
# wind_speed_preview_time: 600
n_turbines: 9
n_wind_field_cases: 6

data_save_dir: /Users/ahenry/Documents/toolboxes/wind-hybrid-open-controller/examples/wind_field_data/raw_data
fig_dir: /Users/ahenry/Documents/toolboxes/wind-hybrid-open-controller/examples/wind_field_data/figs

# probability of any given turbine going offline at each time-step
offline_probability: 0.0

wind_speed:
  range: [3.0, 11.0]
  u_range: [6.0, 11.0]
  v_range: [-3.0, 3.0]
  var: 0.2
  # probability of wind speed/direction changing (1/2 for increase 1/2 for decrease)
  change_probability: 0.25
  turb_std: 1.0
  sampling_time_step: 1.0
  u_noise_args:
    scale: 1.0
  v_noise_args:
    scale: 1.0
  # the noise added within the time-series generate function not suitable for preview joint distribution noise np.random.poisson
  noise_func: np.random.normal

wind_dir:
  range: [250.0, 270.0]
  var: 2.5
  change_probability: 0.25
  turb_std: 2.5
  sampling_time_step: 60.0

yaw_angles:
  range: [-30.0, 30.0]
  var: 1.0
  change_probability: 0.0
  turb_std: 0.0
  sampling_time_step: 60.0
  roc: 0.5

ai_factors:
  range: [0, 1 / 3]
  var: 0.01
  change_probability: 0.0
  turb_std: 0.0
  sampling_time_step: 1.0